name: Publisher

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: contains(github.event.commits[0].message, '(release)') == true
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: trmv
            asset_name: trmv-linux-amd64
          - os: windows-latest
            artifact_name: trmv.exe
            asset_name: trmv-windows-amd64
          - os: macos-latest
            artifact_name: trmv
            asset_name: trmv-macos-amd64

    steps:
    - uses: actions/checkout@v2

    - name: Build for ${{ matrix.os }}
      run: cargo build --release

    - name: Upload binary to release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

